name = "Minecraft Modpack First"
author = "hryvnia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c9f07d8ec56e41dac01fca24bc32386f1f6d184dc8f6505642f63e8656c1975"

[versions]
forge = "43.5.0"
minecraft = "1.19.2"
