name = "Minecraft Modpack First"
author = "hryvnia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1ef3c19a358726a8de5087b68e7c9757d6852469742957f397ae4290133a3fd"

[versions]
forge = "43.5.0"
minecraft = "1.19.2"
