name = "Spontan"
author = "hryvnia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5df9bf9ef434220a55ea9e259a741a3febc2121537bfa92c889749620634e5d8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
