name = "Spontan"
author = "hryvnia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6429ddfb5c376fd68cac04202fddf7b9fc83557e099bc864879cddb348fdd7d8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
