name = "Spontan"
author = "hryvnia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff72e75807133e40cef22c453963c9ffb098336c762f8c477d8615c86b8370a2"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
