name = "Base"
author = "hryvnia"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b58466791e0fef8fe53d47db764d4611352303ac2066c91918004efce457ec30"

[versions]
forge = "43.5.0"
minecraft = "1.19.2"
